### ISSUE TITLE
Error in console after closing Blender

### ISSUE THREAD

**Issue by xan2622** [InamuraJIN/ActionRecorder#18]
Blender version : 2.91 official
Add-on version: 3.5.6

When you close Blender, you can see the following error in the console : 

```
Exception in module unregister(): 'C:\\Users\\xan2622\\AppData\\Roaming\\Blender Foundation\\Blender\\2.91\\scripts\\addons\\ActionRecorder-master\\__init__.py'
Traceback (most recent call last):
  File "E:\blender_Portable\2.91\scripts\modules\addon_utils.py", line 434, in disable
    mod.unregister()
  File "C:\Users\xan2622\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\ActionRecorder-master\__init__.py", line 27, in unregister
    bpy.utils.unregister_class(cls)
RuntimeError: unregister_class(...):, missing bl_rna attribute from 'RNAMeta' instance (may not be registered)
```

**Comment by xan2622** [comment]
It doesn't seem to happen anymore. Maybe it was only on my end.
