### ISSUE TITLE
Error when deactivating Action Recorder 3.5.6

### ISSUE THREAD

**Issue by xan2622** [InamuraJIN/ActionRecorder#19]
Blender version: 2.91
Add-on version: 3.5.6

In Preferences > Addons, if you just deactivate "Action Recorder" (not "Remove"), you should see this message: 

```
Traceback (most recent call last):
  File "E:\blender_portable\2.91\scripts\modules\addon_utils.py", line 434, in disable
    mod.unregister()
  File "C:\Users\Sebastien\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\ActionRecorder-master\__init__.py", line 27, in unregister
    bpy.utils.unregister_class(cls)
RuntimeError: unregister_class(...):, missing bl_rna attribute from 'RNAMeta' instance (may not be registered)
```

**Comment by RivinHD** [comment]
Do these errors always appear when you start Blender? 
I have tested it, but it doesn't happen on my Blender.

**Comment by xan2622** [comment]
It doesn't seem to happen anymore. Maybe the error was on my end.
