### ISSUE TITLE
Blender 4.0 - error with SubdivisionSurface

### ISSUE THREAD

**Issue by vm2023vm** [InamuraJIN/ActionRecorder#57]
**Describe the bug**
Thanks for a very useful addon.
In Blender 4.0, when trying to write a sequence of commands SubdivisionSurface with a value greater than 1, an error appears:

" Python: Traceback (most recent call last):
  File "C:\Users\design\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\ActionRecorder\actrec\operators\locals.py", line 439, in execute
    copy_dict = functions.create_object_copy(context, parent, name)
  File "C:\Users\design\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\ActionRecorder\actrec\functions\macros.py", line 574, in create_object_copy
    id_object = get_id_object(context, source_path, attribute)
  File "C:\Users\design\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\ActionRecorder\actrec\functions\macros.py", line 506, in get_id_object
    return trace_object(context, source_path)
  File "C:\Users\design\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\ActionRecorder\actrec\functions\macros.py", line 523, in trace_object
    index = int(index_str.replace("]", ""))
ValueError: invalid literal for int() with base 10: '"Subdivision"'

**To Reproduce**
- LocalActions "+"
- Record
- AddModifier "Subdivision Surface"
- Change value Levels viewport "3"
- Stop
- Have bug report aforecited

**Expected behavior**
recording a sequence of actions

**Screenshots**
![screen](https://github.com/InamuraJIN/ActionRecorder/assets/151816082/2dc48d2e-f08e-4b17-98be-c4750e12f9af)

**Version Information:**
 - Add-on Version 4.0.8
 - Blender Version 4.0
 - OS:  Windows 10

**Additional context**
Thanks again for the wonderful addon

**Comment by RivinHD** [comment]
Fixed with [Version 4.0.1](https://github.com/InamuraJIN/ActionRecorder/releases/tag/v4.1.0)
